name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - ['*'] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v src/oh-plugin_test.go

